spring:
  application:
    name: service-gateway-server
  profiles:
    active: production
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: '*'
  prefix: ''
  routes:
    service-emaillist: /emaillist/**
