spring:
  application:
    name: service-config-server
  profiles:
    active: git
server:
  port: 7777
encrypt:
  key-store:
    alias: selfsigned
    location: classpath:keystore.jks
    password: password

---
#
# configuration based on git
#
spring:
  config:
    activate:
      on-profile: git
  cloud:
    config:
      server:
        encrypt.enabled: true
        git:
          uri: https://github.com/kimjunho12/msa-practices-config
          searchPaths: service-emaillist, service-gallery, service-storage, service-guestbook
logging:
  pattern:
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
      max-file-size: 10MB
      max-history: 10
  file:
    name: logs/${spring.application.name}.log
  level:
    root: WARN

---
#
# configuration based on file-system(native)
#
spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        encrypt.enabled: true
        native:
          searchLocations:
            file:D:/BIT/STS-workspace/msa-practices-config/service-emaillist,
            file:D:/BIT/STS-workspace/msa-practices-config/service-gallery,
            file:D:/BIT/STS-workspace/msa-practices-config/service-storage,
            file:D:/BIT/STS-workspace/msa-practices-config/service-guestbook
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
  level:
    root: INFO
